### ISSUE TITLE
Null reference exception often occur on locating the anchor.

### ISSUE THREAD

**Issue by TakahiroMiyaura** [TakahiroMiyaura/WayFindingSamplesUsingASA#5]
On locating the anchor, null reference exception occur. 
This is because I don't take in consider the base point operation.

**Comment by Bing873** [comment]
When I try to run your project, there is one script missing for Prefab RouteCollection. May I ask which script should it be? Thank you!

**Comment by TakahiroMiyaura** [comment]
Hi Bing873,

Thank you for your information.
I'm checking my project now, but I can't find the issue that you've reported.

If time allows, may I tell me the details?
 
* When you try to open SampleScene.unity?
* When you try to do Unity Build?
* When you try to build it on Visual Studio? 
* If there is the error log, I want tell me the information.
* etc...

I check the below:

[Environment]
* Unity 2019.2.18
* Azure Spatial Anchors 2.2.1
* Mixed Reality Toolkit 2.3.0

[Process]
1. Clone this repository.
2. Open Unity Project (In this time, there are some errors.)
3. Import MRTK 2.3.0. 
    1. Download [Microsoft.MixedReality.Toolkit.Unity.Foundation.2.3.0.unitypackage](https://github.com/microsoft/MixedRealityToolkit-Unity/releases/tag/v2.3.0)
    2. Select Menu [Asset]-[Import Package]-[Custom Package]
    3. Import  Microsoft.MixedReality.Toolkit.Unity.Foundation.2.3.0.unitypackage
4. Import Azure Spatial Anchors.
    1. Download [AzureSpatialAnchors.unitypackage](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.2.1)
    2. Select Unity Menu [Asset]-[Import Package]-[Custom Package]
    3. Import  AzureSpatialAnchors.unitypackag
5. Open SampleScene.
6. Select module\AnchorModule\Main in Hierarchy panel, and set  ASA Account ID, Key to SpatialAnchorManager in Inspector panel.
7. Open Unity Menu [File]-[Build Settings], and set the below:
    * platform : Universal Windows Platform
8. Select Menu [Mixed Reality Toolkit]-[Utilities]-[Configure Unity Project], and Put all check marks.
9. Select Menu [Edit]-[Project Settings], set the below:
    * Put a check mark of Virtual Reality Supported in XR Settings.
    * Add  Windows Mixed Reality SDK in Virtual Reality SDKs, Change 16bit to Depth Format.
    * Put a check mark in [Publish Settings]-[Capabilities]
        * InternetClient
        * InternetClientServer
        * RemovableStorage
        * SpatialPerception

Best Regards,

**Comment by Bing873** [comment]
Thank you for the detailed instruction, Takahiro! 

Following your steps, now I can create a route using ASA successfully. However, when I try to restart the app and find the loaded anchors ("Find Azure Anchor"), the development console throws Error: Cannot run more than one watcher concurrently in this SDK version. Request CV: . Response CV: .  Does this occur to you as well? And how to solve it? Thanks a lot. 

PS. I'm sure you have noticed this, but in case someone else is as new as myself: to use a new ASA Account with ASA 2.2.1, the "Domain" has to be set to "East US 2", as an influence of [a major change in v2.4.0](https://github.com/Azure/azure-spatial-anchors-samples/releases).

**Comment by TakahiroMiyaura** [comment]
Thank you, Bing873!

Thanks to you, I could remember that I must upgrade this project to ASA version  2.7.0 SDK or later.
The reason for this mandatory upgrade is that Azure Spatial Anchors service is being impacted by the move away from Baltimore CyberTrust Root CA (https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.7.0).

To fix this problem I create new issue #9. 
If you confirm this comment, this issue will be closed, and I’ll fix #9 on and after.

Best Regards,
Takahiro

**Comment by Bing873** [comment]
Hey Takahiro. Yes, that seems to be the cause. Thank you for your timely response and the efforts to fix it. :D

Greetings,
Bing
